package Model;
// Generated 11-22-2016 04:28:26 PM by Hibernate Tools 4.3.1



/**
 * CedulaId generated by hbm2java
 */
public class CedulaId  implements java.io.Serializable {


     private int idCliente;
     private String numeroCedula;

    public CedulaId() {
    }

    public CedulaId(int idCliente, String numeroCedula) {
       this.idCliente = idCliente;
       this.numeroCedula = numeroCedula;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNumeroCedula() {
        return this.numeroCedula;
    }
    
    public void setNumeroCedula(String numeroCedula) {
        this.numeroCedula = numeroCedula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CedulaId) ) return false;
		 CedulaId castOther = ( CedulaId ) other; 
         
		 return (this.getIdCliente()==castOther.getIdCliente())
 && ( (this.getNumeroCedula()==castOther.getNumeroCedula()) || ( this.getNumeroCedula()!=null && castOther.getNumeroCedula()!=null && this.getNumeroCedula().equals(castOther.getNumeroCedula()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCliente();
         result = 37 * result + ( getNumeroCedula() == null ? 0 : this.getNumeroCedula().hashCode() );
         return result;
   }   


}


