package Model;
// Generated 11-22-2016 04:28:26 PM by Hibernate Tools 4.3.1



/**
 * Cedula generated by hbm2java
 */
public class Cedula  implements java.io.Serializable {


     private CedulaId id;
     private Cliente cliente;

    public Cedula() {
    }

    public Cedula(CedulaId id, Cliente cliente) {
       this.id = id;
       this.cliente = cliente;
    }
   
    public CedulaId getId() {
        return this.id;
    }
    
    public void setId(CedulaId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


