package Model;
// Generated 11-22-2016 04:28:26 PM by Hibernate Tools 4.3.1



/**
 * DetallecompraId generated by hbm2java
 */
public class DetallecompraId  implements java.io.Serializable {


     private int idProducto;
     private int idCompra;

    public DetallecompraId() {
    }

    public DetallecompraId(int idProducto, int idCompra) {
       this.idProducto = idProducto;
       this.idCompra = idCompra;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public int getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(int idCompra) {
        this.idCompra = idCompra;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallecompraId) ) return false;
		 DetallecompraId castOther = ( DetallecompraId ) other; 
         
		 return (this.getIdProducto()==castOther.getIdProducto())
 && (this.getIdCompra()==castOther.getIdCompra());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProducto();
         result = 37 * result + this.getIdCompra();
         return result;
   }   


}


