package Model;
// Generated 11-22-2016 04:28:26 PM by Hibernate Tools 4.3.1



/**
 * DetallefaturaId generated by hbm2java
 */
public class DetallefaturaId  implements java.io.Serializable {


     private int idProducto;
     private int idFactura;

    public DetallefaturaId() {
    }

    public DetallefaturaId(int idProducto, int idFactura) {
       this.idProducto = idProducto;
       this.idFactura = idFactura;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallefaturaId) ) return false;
		 DetallefaturaId castOther = ( DetallefaturaId ) other; 
         
		 return (this.getIdProducto()==castOther.getIdProducto())
 && (this.getIdFactura()==castOther.getIdFactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProducto();
         result = 37 * result + this.getIdFactura();
         return result;
   }   


}


