package Model;
// Generated 11-22-2016 04:28:26 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra  implements java.io.Serializable {


     private DetallecompraId id;
     private Compra compra;
     private Producto producto;
     private BigDecimal costo;
     private Integer cantidad;
     private Integer cantidadDisponible;
     public int CantidadLlevar;

    public Detallecompra() {
    }

	
    public Detallecompra(DetallecompraId id, Compra compra, Producto producto) {
        this.id = id;
        this.compra = compra;
        this.producto = producto;
    }
    public Detallecompra(DetallecompraId id, Compra compra, Producto producto, BigDecimal costo, Integer cantidad, Integer cantidadDisponible) {
       this.id = id;
       this.compra = compra;
       this.producto = producto;
       this.costo = costo;
       this.cantidad = cantidad;
       this.cantidadDisponible = cantidadDisponible;
    }
   
    public DetallecompraId getId() {
        return this.id;
    }
    
    public void setId(DetallecompraId id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getCantidadDisponible() {
        return this.cantidadDisponible;
    }
    
    public void setCantidadDisponible(Integer cantidadDisponible) {
        this.cantidadDisponible = cantidadDisponible;
    }

    public int getCantidadLlevar() {
        return CantidadLlevar;
    }

    public void setCantidadLlevar(int CantidadLlevar) {
        this.CantidadLlevar = CantidadLlevar;
    }
    
    




}


