package Model;
// Generated 11-22-2016 04:28:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private Empleado empleado;
     private Date fecha;
     private Set detallefaturas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Date fecha) {
        this.fecha = fecha;
    }
    public Factura(Cliente cliente, Empleado empleado, Date fecha, Set detallefaturas) {
       this.cliente = cliente;
       this.empleado = empleado;
       this.fecha = fecha;
       this.detallefaturas = detallefaturas;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetallefaturas() {
        return this.detallefaturas;
    }
    
    public void setDetallefaturas(Set detallefaturas) {
        this.detallefaturas = detallefaturas;
    }




}


