package Model;
// Generated 11-22-2016 04:28:26 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Categoria categoria;
     private String nombreProducto;
     private String marca;
     private String descripcion;
     private BigDecimal precioCompra;
     private BigDecimal precioVenta;
     private BigDecimal ultimoPv;
     private Integer stock;
     private Boolean estado;
     private Set detallecompras = new HashSet(0);
     private Set detallefaturas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String marca, String descripcion, BigDecimal ultimoPv) {
        this.marca = marca;
        this.descripcion = descripcion;
        this.ultimoPv = ultimoPv;
    }
    public Producto(Categoria categoria, String nombreProducto, String marca, String descripcion, BigDecimal precioCompra, BigDecimal precioVenta, BigDecimal ultimoPv, Integer stock, Boolean estado, Set detallecompras, Set detallefaturas) {
       this.categoria = categoria;
       this.nombreProducto = nombreProducto;
       this.marca = marca;
       this.descripcion = descripcion;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
       this.ultimoPv = ultimoPv;
       this.stock = stock;
       this.estado = estado;
       this.detallecompras = detallecompras;
       this.detallefaturas = detallefaturas;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public BigDecimal getUltimoPv() {
        return this.ultimoPv;
    }
    
    public void setUltimoPv(BigDecimal ultimoPv) {
        this.ultimoPv = ultimoPv;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }
    public Set getDetallefaturas() {
        return this.detallefaturas;
    }
    
    public void setDetallefaturas(Set detallefaturas) {
        this.detallefaturas = detallefaturas;
    }




}


