package Model;
// Generated 11-22-2016 04:28:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String nombreProveedor;
     private String telefono;
     private String ruc;
     private Date fechaRegistro;
     private Boolean estado;
     private Set representantes = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String telefono, String ruc) {
        this.telefono = telefono;
        this.ruc = ruc;
    }
    public Proveedor(String nombreProveedor, String telefono, String ruc, Date fechaRegistro, Boolean estado, Set representantes) {
       this.nombreProveedor = nombreProveedor;
       this.telefono = telefono;
       this.ruc = ruc;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.representantes = representantes;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getRepresentantes() {
        return this.representantes;
    }
    
    public void setRepresentantes(Set representantes) {
        this.representantes = representantes;
    }




}


