/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.C_Categoria;
import Model.Categoria;
import Render.ModelCategoria;
import Validations.Validate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ahrhe
 */
public class V_Categorias extends javax.swing.JInternalFrame {

    /**
     * Creates new form V_Categorias
     */
    
    boolean nuevo=false, editar=false;
    int idCategoria=0;
    C_Categoria ccat = new C_Categoria();    
    ModelCategoria mc;
    Validate v =new Validate();
    
    public V_Categorias() {
        initComponents();
        mc = new ModelCategoria(ccat.findAll());
        jTable1.setModel(mc);
        mc.ColumnSize(jTable1);
        this.disableFields();
    }
    
     public void disableFields(){
        txt_nombreCategoria1.setEnabled(false);
        txt_descripcionCategoria1.setEnabled(false);
    }
    
    public void enableFields(){
        txt_nombreCategoria1.setEnabled(true);
        txt_descripcionCategoria1.setEnabled(true);
    }
    
    public void clearFields(){
        txt_nombreCategoria1.setText("");
        txt_descripcionCategoria1.setText("");
    }
    
    public void enableEdit(){
        btn_editar.setEnabled(false);
        btn_nuevo2.setEnabled(false);
        btn_guardar2.setEnabled(true);
        this.editar=true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalManejoCategoria = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btn_nuevo2 = new javax.swing.JButton();
        btn_guardar2 = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_cancelar2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoBuscar = new javax.swing.JTextField();
        btn_buscarTexto2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txt_nombreCategoria1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descripcionCategoria1 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Gestión de Categorías");

        PanelPrincipalManejoCategoria.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setBackground(javax.swing.UIManager.getDefaults().getColor("ToggleButton.light"));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btn_nuevo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/address-book-new.png"))); // NOI18N
        btn_nuevo2.setToolTipText("Nuevo Elemento");
        btn_nuevo2.setFocusable(false);
        btn_nuevo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nuevo2.setOpaque(false);
        btn_nuevo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo2ActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_nuevo2);

        btn_guardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/document-save-all.png"))); // NOI18N
        btn_guardar2.setToolTipText("Guardar Datos");
        btn_guardar2.setFocusable(false);
        btn_guardar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardar2.setOpaque(false);
        btn_guardar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar2ActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_guardar2);

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/document-edit.png"))); // NOI18N
        btn_editar.setToolTipText("Editar");
        btn_editar.setFocusable(false);
        btn_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_editar.setOpaque(false);
        btn_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_editar);

        btn_cancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dialog-cancel.png"))); // NOI18N
        btn_cancelar2.setToolTipText("Cancelar ");
        btn_cancelar2.setFocusable(false);
        btn_cancelar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cancelar2.setOpaque(false);
        btn_cancelar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar2ActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_cancelar2);
        jToolBar2.add(jSeparator1);

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit-find-project.png"))); // NOI18N
        btn.setToolTipText("Buscar Registro");
        btn.setFocusable(false);
        btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn.setOpaque(false);
        btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jToolBar2.add(btn);

        jLabel2.setText("Búsqueda por Nombre  ");
        jToolBar2.add(jLabel2);

        btn_buscarTexto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_find2.png"))); // NOI18N
        btn_buscarTexto2.setToolTipText("Buscar");
        btn_buscarTexto2.setFocusable(false);
        btn_buscarTexto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_buscarTexto2.setOpaque(false);
        btn_buscarTexto2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_buscarTexto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarTexto2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(textoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscarTexto2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarTexto2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jToolBar2.add(jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle de Categoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 18))); // NOI18N

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel12.setText("Nombre de la Categoría :");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel13.setText("Descripcion de la Categoría :");

        txt_descripcionCategoria1.setColumns(20);
        txt_descripcionCategoria1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txt_descripcionCategoria1.setLineWrap(true);
        txt_descripcionCategoria1.setRows(5);
        jScrollPane2.setViewportView(txt_descripcionCategoria1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombreCategoria1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de las Categorías", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 18))); // NOI18N
        jPanel8.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel8.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout PanelPrincipalManejoCategoriaLayout = new javax.swing.GroupLayout(PanelPrincipalManejoCategoria);
        PanelPrincipalManejoCategoria.setLayout(PanelPrincipalManejoCategoriaLayout);
        PanelPrincipalManejoCategoriaLayout.setHorizontalGroup(
            PanelPrincipalManejoCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalManejoCategoriaLayout.createSequentialGroup()
                .addGroup(PanelPrincipalManejoCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        PanelPrincipalManejoCategoriaLayout.setVerticalGroup(
            PanelPrincipalManejoCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalManejoCategoriaLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipalManejoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipalManejoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo2ActionPerformed
        ///this.table.setModel(modelTableEmpleado);

        //this.EnableFields(true);
        //this.EnableFind(true);
        this.enableFields();
        this.clearFields();
        this.txt_nombreCategoria1.requestFocus();
        nuevo = true;      editar = false;
    }//GEN-LAST:event_btn_nuevo2ActionPerformed

    private void btn_guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar2ActionPerformed

        if(nuevo){

            this.enableFields();
            JOptionPane.showMessageDialog(null,ccat.create(txt_nombreCategoria1.getText(), txt_descripcionCategoria1.getText()));
            mc.fireTableDataChanged();
            this.clearFields();
            mc.Clear();
            this.nuevo = false;     this.editar = false;
            jTable1.setModel(mc);
        }
        if(editar){
            this.enableFields();

            JOptionPane.showMessageDialog(null, ccat.update(idCategoria,txt_nombreCategoria1.getText(), txt_descripcionCategoria1.getText()));
            mc.fireTableDataChanged();

            this.clearFields();
            this.nuevo = false;     this.editar = false;
        }

    }//GEN-LAST:event_btn_guardar2ActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        this.enableFields();

        nuevo = false;      editar = true;
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar2ActionPerformed

        //this.EnableFields(false);
        //this.EnableFind(true);
        //this.Clear();

    }//GEN-LAST:event_btn_cancelar2ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        //this.EnableFind(true);
    }//GEN-LAST:event_btnActionPerformed

    private void btn_buscarTexto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarTexto2ActionPerformed
        this.disableFields();

        if (!textoBuscar.getText().equals("")) {
            C_Categoria ccate = new C_Categoria();
            mc.Clear();
            List<Categoria> lista = ccate.busquedaporNombre(textoBuscar.getText());

            for(Categoria cate : lista){
                mc.addRow(cate);
            }

        }else{
            if (jTable1.getRowCount()< ccat.findAll().size()) {
                for(Categoria cate : ccat.findAll() ){
                    mc.addRow(cate);
                }
            }

        }

    }//GEN-LAST:event_btn_buscarTexto2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int NClic = evt.getClickCount();

        if (NClic >= 2) {
            idCategoria = (Integer) mc.getValueAt(jTable1.getSelectedRow(), 0);
            txt_nombreCategoria1.setText((String) mc.getValueAt(jTable1.getSelectedRow(), 1));
            txt_descripcionCategoria1.setText((String) mc.getValueAt(jTable1.getSelectedRow(), 2));

        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipalManejoCategoria;
    private javax.swing.JButton btn;
    private javax.swing.JButton btn_buscarTexto2;
    private javax.swing.JButton btn_cancelar2;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_guardar2;
    private javax.swing.JButton btn_nuevo2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField textoBuscar;
    private javax.swing.JTextArea txt_descripcionCategoria1;
    private javax.swing.JTextField txt_nombreCategoria1;
    // End of variables declaration//GEN-END:variables
}
