/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.C_DetalleFactura;
import Controler.C_Factura;
import DAO.EmpleadoDAO;
import Model.Detallefatura;
import Model.Empleado;
import Render.ModelDetalleFactura;
import Render.ModelProductoCompra;
import Render.ModelTableCompraProducto;
import Validations.Validate;
import Validations.WindowsDrive;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author Allan Ramirez
 */
public class V_Factura extends javax.swing.JInternalFrame {

    /**
     * Creates new form V_Factura
     */
    
    //Paso 1
    public static int idCliente, idEmpleado, idFactura =0;
    public static ModelDetalleFactura model;
    Validate v = new Validate();
    EmpleadoDAO empdao = new EmpleadoDAO();
    Empleado emp = empdao.find(Principal.getUser().getIdEmpleado());
    C_Factura cfact = new C_Factura();
    C_DetalleFactura cdet = new C_DetalleFactura();
    
    
    public V_Factura() {
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
        Date date = new Date();
        txt_Fecha.setText(dateFormat.format(date));
        
        model = new ModelDetalleFactura(new ArrayList());
        table.setModel(model);
        model.ColumnSize(table);
        
        txt_nombreEmp.setText(emp.getNombre()+ " "+ emp.getApellido());
        idEmpleado = emp.getIdEmpleado();
        jLabel6.setText("Factura Nº "+ cfact.siguienteFactura());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosCompras = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_Fecha = new javax.swing.JFormattedTextField();
        txt_nombreEmp = new javax.swing.JTextField();
        btn_BuscarCliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_Telefono = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_NumeroCedula = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        panelTablaCompras = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        btn_quitar = new javax.swing.JButton();
        btn_editarCantidad = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        lbl_IVA = new javax.swing.JLabel();
        lbl_Subtotal = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestión de Factura");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_factura.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(800, 675));
        setMinimumSize(new java.awt.Dimension(800, 675));
        setPreferredSize(new java.awt.Dimension(800, 675));

        panelDatosCompras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Factura", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setText("Nombre del Cliente :");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Fecha :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Empleado:");

        txt_nombreCliente.setEditable(false);
        txt_nombreCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreClienteActionPerformed(evt);
            }
        });

        txt_Fecha.setEditable(false);
        txt_Fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyYY"))));
        txt_Fecha.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txt_nombreEmp.setEditable(false);
        txt_nombreEmp.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btn_BuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/text-x-ldif2px.png"))); // NOI18N
        btn_BuscarCliente.setToolTipText("Buscar Cliente");
        btn_BuscarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarClienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setText("Teléfono :");

        txt_Telefono.setEditable(false);
        try {
            txt_Telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Numero Cédula :");

        txt_NumeroCedula.setEditable(false);
        try {
            txt_NumeroCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_NumeroCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NumeroCedulaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Factura Nº ");

        javax.swing.GroupLayout panelDatosComprasLayout = new javax.swing.GroupLayout(panelDatosCompras);
        panelDatosCompras.setLayout(panelDatosComprasLayout);
        panelDatosComprasLayout.setHorizontalGroup(
            panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombreCliente)
                    .addComponent(txt_NumeroCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(txt_Telefono))
                .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosComprasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombreEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosComprasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(85, 85, 85))))
        );
        panelDatosComprasLayout.setVerticalGroup(
            panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosComprasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosComprasLayout.createSequentialGroup()
                        .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosComprasLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_nombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(panelDatosComprasLayout.createSequentialGroup()
                        .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_NumeroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDatosComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(12, 12, 12))))
        );

        panelTablaCompras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de los Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 18))); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1, 0, 5));

        btn_agregar.setBackground(new java.awt.Color(153, 153, 153));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fac_addproduct.png"))); // NOI18N
        btn_agregar.setText("Nuevo");
        btn_agregar.setToolTipText("Nuevo producto");
        btn_agregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agregar);

        btn_quitar.setBackground(new java.awt.Color(153, 153, 153));
        btn_quitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fac_remove.png"))); // NOI18N
        btn_quitar.setText("Remover");
        btn_quitar.setToolTipText("Eliminar producto");
        btn_quitar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_quitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quitar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_quitar);

        btn_editarCantidad.setBackground(new java.awt.Color(153, 153, 153));
        btn_editarCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fac_editproduct.png"))); // NOI18N
        btn_editarCantidad.setText("Editar");
        btn_editarCantidad.setToolTipText("Editar producto");
        btn_editarCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_editarCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_editarCantidad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_editarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarCantidadActionPerformed(evt);
            }
        });
        jPanel2.add(btn_editarCantidad);

        btn_Guardar.setBackground(new java.awt.Color(153, 153, 153));
        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fac_save.png"))); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.setToolTipText("Guardar factura");
        btn_Guardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Guardar);

        btn_Cancelar.setBackground(new java.awt.Color(153, 153, 153));
        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fac_cancel.png"))); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setToolTipText("Cancelar");
        btn_Cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cancelar);

        javax.swing.GroupLayout panelTablaComprasLayout = new javax.swing.GroupLayout(panelTablaCompras);
        panelTablaCompras.setLayout(panelTablaComprasLayout);
        panelTablaComprasLayout.setHorizontalGroup(
            panelTablaComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTablaComprasLayout.setVerticalGroup(
            panelTablaComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaComprasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTablaComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(174, 174, 174))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monto de factura", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Monotype Corsiva", 2, 14), new java.awt.Color(0, 51, 153))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Subtotal :");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("I.V.A :");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Total :");

        lbl_Total.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_Total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbl_IVA.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_IVA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbl_Subtotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_Subtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lbl_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTablaCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTablaCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarClienteActionPerformed
        Thread th = new Thread(()
            -> {
                new WindowsDrive().WindowDriver(new Int_Popup(3), this.getDesktopPane());
            });
            th.start();
            
        
    }//GEN-LAST:event_btn_BuscarClienteActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        Thread th = new Thread(()
            -> {
                new WindowsDrive().WindowDriver(new Int_Popup(2), this.getDesktopPane());
            });
            th.start();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
        int row = this.table.getSelectedRow();
        if (table.getSelectedRow()!=-1) {
            model.removeRow(row);
        }
        
                try{
        
                BigDecimal subtotal= BigDecimal.ZERO;
                BigDecimal impuesto;
                BigDecimal total=new BigDecimal(0);
                BigDecimal monto = BigDecimal.ZERO;
                
                for (int i = 0; i< model.getRowCount(); i++) {
//                    System.out.println("monto: "+(BigDecimal)model.getValueAt(i,5));
                    monto = (BigDecimal)model.getValueAt(i,5);
                    subtotal = (subtotal.add(monto));                   
                }
                impuesto = subtotal.multiply(new BigDecimal(0.15));
                System.out.println("Table listener");
                 
                total = subtotal.add(impuesto);

              V_Factura.lbl_Subtotal.setText(""+subtotal.setScale(2, RoundingMode.DOWN));
              V_Factura.lbl_IVA.setText(""+impuesto.setScale(2,RoundingMode.DOWN));
              V_Factura.lbl_Total.setText(""+total.setScale(2,RoundingMode.DOWN));
              
                }catch(NumberFormatException nfe){
                    nfe.printStackTrace();
                }
              
    }//GEN-LAST:event_btn_quitarActionPerformed

    private void btn_editarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarCantidadActionPerformed
        int row = this.table.getSelectedRow();
        if (table.getSelectedRow()!=-1) {
            boolean band =true;
            int cant=0;
            do {
                try {
                    cant = v.Integer(JOptionPane.showInputDialog(null, "Ingrese nueva cantidad"));
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Ingrese solo Numeros");
                    band = false;
                }

            } while (band != true);

            model.cambiarCantidad(row, cant);

        }else
        JOptionPane.showMessageDialog(this, "Seleccione un producto primero");
        
        BigDecimal subtotal= new BigDecimal(0);
                BigDecimal impuesto;
                BigDecimal total=new BigDecimal(0);
                
                for (int i = 0; i< model.getRowCount(); i++) {
                    subtotal.add((BigDecimal)model.getValueAt(i,5));
                }
                
                impuesto = subtotal.multiply(new BigDecimal(0.15));
                System.out.println("Table listener");
                
                total = subtotal.add(impuesto);

              V_Factura.lbl_Subtotal.setText(""+subtotal.setScale(2, RoundingMode.DOWN));
              V_Factura.lbl_IVA.setText(""+impuesto.setScale(2,RoundingMode.DOWN));
              V_Factura.lbl_Total.setText(""+total.setScale(2,RoundingMode.DOWN));
                
    }//GEN-LAST:event_btn_editarCantidadActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        //Paso 2
        if (idCliente!= -1) {
            //Recoger Datos
            //Paso 3
            C_Factura factura =new C_Factura();
            C_DetalleFactura cdet = new C_DetalleFactura();
            //paso 5
            if (table.getRowCount()>=1) {
                //paso 7
                for (int i = 0; i < table.getRowCount(); i++) {
                //Paso 8
                Detallefatura detfa = cdet.setDetallefatura((Integer) table.getValueAt(i, 0),(BigDecimal) table.getValueAt(i, 4), (Integer) table.getValueAt(i,3), Float.parseFloat("0.0"));
                factura.nuevaFactura(detfa);
                
            }
            //paso 9
            JOptionPane.showMessageDialog(this, factura.guardarFactura(idCliente, idEmpleado));
            
            //Limpiar campos
            
            idCliente= -1;
            }else{
                //paso 6
                JOptionPane.showMessageDialog(rootPane, "Debe haber agregado un producto.");
            }
            
            
            
        }else{
            //Paso 4
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un cliente en especifico");
        }
        
        
        
        
        BigDecimal st=BigDecimal.ZERO, iva=BigDecimal.ZERO, t=BigDecimal.ZERO;
        st = v.String_BigDecimal(this.lbl_Subtotal.getText());
        iva = v.String_BigDecimal(this.lbl_IVA.getText());
        t = v.String_BigDecimal(this.lbl_Total.getText());
        
        C_Factura.PrintReport(st, iva, t);

    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void txt_nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreClienteActionPerformed

    private void txt_NumeroCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NumeroCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NumeroCedulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarCliente;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_editarCantidad;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbl_IVA;
    public static javax.swing.JLabel lbl_Subtotal;
    public static javax.swing.JLabel lbl_Total;
    private javax.swing.JPanel panelDatosCompras;
    private javax.swing.JPanel panelTablaCompras;
    private javax.swing.JTable table;
    private javax.swing.JFormattedTextField txt_Fecha;
    public static javax.swing.JFormattedTextField txt_NumeroCedula;
    public static javax.swing.JFormattedTextField txt_Telefono;
    public static javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_nombreEmp;
    // End of variables declaration//GEN-END:variables
}
